// Halaman detail antrean dokter untuk verifikasi hasil deteksi AI.
// Menampilkan gambar X-ray, diagnosis AI, CTR ratio, gejala, dan catatan dokter.

"use client";

import { useEffect, useState, Suspense } from "react";
import { useRouter, useParams } from "next/navigation";
import Image from "next/image";
import { apiFetch, getSavedSession, getMediaUrl, useSafeImageSrc } from "@/utils/api";

interface PatientDetail {
  id: string;
  patientName: string;
  age: number;
  gender: string;
  uploadDate: string;
  aiPrediction: string;
  confidence: number;
  symptoms: string;
  xrayUrl: string;
  ctrRatio: string;
  heartSize: string;
  bloodType: string;
  allergies: string;
  aiInsight?: string;
}

function DetailAnalysisContent() {
  const router = useRouter();
  const params = useParams();

  const patientId = params.patientId as string;
  const scanId = patientId || "REF-99281-XC";

  const [patient, setPatient] = useState<PatientDetail>({
    id: scanId,
    patientName: "",
    age: 0,
    gender: "",
    uploadDate: "",
    aiPrediction: "",
    confidence: 0,
    symptoms: "",
    xrayUrl: "/common/xray-base.png",
    ctrRatio: "0.50",
    heartSize: "Normal",
    bloodType: "",
    allergies: "",
    aiInsight: ""
  });

  const safeXrayUrl = useSafeImageSrc(patient.xrayUrl, "/common/xray-base.png");

  const [loading, setLoading] = useState(true);
  const [doctorNotes, setDoctorNotes] = useState("");
  const [doctorAssessment, setDoctorAssessment] = useState("Cardiomegaly");
  const [aiAccuracyConfirmed, setAiAccuracyConfirmed] = useState(true);
  const [ecgRequired, setEcgRequired] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  const getAge = (dobString: string | undefined) => {
    if (!dobString) return 30;
    try {
      const birth = new Date(dobString);
      const now = new Date();
      let age = now.getFullYear() - birth.getFullYear();
      const m = now.getMonth() - birth.getMonth();
      if (m < 0 || (m === 0 && now.getDate() < birth.getDate())) {
        age--;
      }
      return age;
    } catch {
      return 30;
    }
  };

  useEffect(() => {
    const session = getSavedSession();
    if (!session || session.role !== "doctor") {
      router.push("/");
      return;
    }

    async function loadDetail() {
      setLoading(true);
      setErrorMsg("");
      try {
        const res = await apiFetch(`/verifications/${scanId}`);
        if (res.success && res.data && res.data.prediction) {
          const item = res.data.prediction;
          const label = item.prediction_label || "Normal";
          
          // TODO [AI]: Tambahin field model AI baru di interface PatientDetail & map di sini
          setPatient({
            id: item.id,
            patientName: item.patient?.full_name || "Unknown Patient",
            age: getAge(item.patient?.date_of_birth),
            gender: "Not Specified",
            uploadDate: item.created_at ? new Date(item.created_at).toLocaleDateString("en-US", { day: "numeric", month: "short", year: "numeric" }) : "Recently",
            aiPrediction: label,
            confidence: item.confidence_score != null ? Math.round(item.confidence_score * 100) : 89, // TODO [AI]: Hapus fallback 89 kalau AI BE udah selalu ngasih confidence_score
            symptoms: item.patient_notes || item.notes || "No symptoms listed.",
            xrayUrl: getMediaUrl(item.image_path) || "/common/xray-base.png",
            ctrRatio: item.ctr_ratio != null ? String(item.ctr_ratio) : "0.50",
            heartSize: item.heart_size || "Normal",
            bloodType: item.patient?.blood_type || "Not Specified",
            allergies: item.patient?.allergies || "Not Specified",
            aiInsight: item.insight || `Cardiothoracic ratio is ${item.ctr_ratio != null ? item.ctr_ratio : '0.50'}. ${label} prediction label generated by live model with ${item.confidence_score != null ? Math.round(item.confidence_score * 100) : 90}% confidence.`
          });
          setDoctorAssessment(label);
        } else {
          setErrorMsg(res.error || "Failed to load patient verification detail.");
        }
      } catch (err: any) {
        console.error("Failed to fetch detail:", err);
        setErrorMsg("Failed to load details from the backend API.");
      } finally {
        setLoading(false);
      }
    }
    loadDetail();
  }, [scanId, router]);

  const handleSubmitVerification = async () => {
    const trimmedNotes = doctorNotes.trim();
    if (!trimmedNotes) {
      setErrorMsg("Please enter your observation notes before sending.");
      return;
    }

    // Security Hardening: Sanitize inputs to prevent stored XSS injection
    const sanitizedNotes = trimmedNotes.replace(/<[^>]*>/g, "");

    setSubmitting(true);
    setErrorMsg("");

    try {
      const res = await apiFetch(`/verifications/${scanId}/verify`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          doctorNotes: sanitizedNotes,
          doctorAssessment,
          aiAccuracyConfirmed,
          ecgRequired
        }),
      });

      if (res.success) {
        router.push(`/doctor/queue/${scanId}/result`);
      } else {
        setErrorMsg(res.error || "Failed to submit verification.");
      }
    } catch (err: any) {
      console.error("Verification submit error:", err);
      setErrorMsg(err.message || "Failed to submit verification request.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="w-full min-h-[400px] flex items-center justify-center bg-fbc rounded-2xl border border-bgelem/40">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
          <p className="text-xs font-bold text-textt">Loading patient details...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Title Block */}
      <div className="flex flex-col gap-1">
        <h2 className="text-xl font-bold text-texts tracking-tight">Verification Queue</h2>
        <p className="text-xs md:text-sm text-textt font-medium">
          Manage and review patient cardiac analysis results digitally.
        </p>
      </div>

      {/* Main Column Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Column (X-Ray and Doctor Notes Input) */}
        <div className="lg:col-span-7 flex flex-col gap-6">
          {/* X-Ray analysis card */}
          <div className="bg-fbc border border-bgelem/30 rounded-2xl p-6 shadow-sm flex flex-col">
            <div className="flex justify-between items-center mb-4">
              <div className="flex items-center gap-2">
                <svg className="w-5 h-5 text-primary" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                <h3 className="text-sm font-bold text-texts tracking-tight">X-Ray Neural Analysis</h3>
              </div>
              <div className="flex items-center gap-1.5 text-[10px] font-bold text-rose-600 bg-rose-50 border border-rose-100 px-2.5 py-1 rounded-full">
                <span className="w-1.5 h-1.5 rounded-full bg-rose-500 animate-pulse"></span>
                Live Engine Processing
              </div>
            </div>

            {/* Neural Viewport with overlay indicators */}
            <div className="relative w-full aspect-[4/3] bg-slate-950 rounded-xl overflow-hidden flex items-center justify-center border border-slate-800">
              {/* Overlay Grid lines */}
              <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:40px_40px] z-10 pointer-events-none"></div>

              {/* The Actual Chest X-Ray Image */}
              <Image
                src={safeXrayUrl}
                alt="Chest X-Ray Scan"
                fill
                className="object-contain opacity-70"
              />

              {/* Bounding Box overlay 1: LV Segment */}
              <div className="absolute border border-dashed border-primary bg-primary/5 p-1 text-[7px] font-mono font-bold text-primary flex flex-col justify-between" style={{ bottom: "25%", right: "32%", width: "22%", height: "20%" }}>
                <span>LV_SEGMENT_04</span>
              </div>

              {/* Bounding Box overlay 2: Aortic Arch highlight */}
              <div className="absolute border border-dashed border-primary bg-primary/5 p-1 text-[7px] font-mono font-bold text-primary flex flex-col justify-between" style={{ top: "35%", left: "45%", width: "10%", height: "10%" }}>
                <span>.</span>
              </div>
            </div>
          </div>

          {/* Doctor Notes Form */}
          <div className="bg-fbc border border-bgelem/30 rounded-2xl p-6 shadow-sm flex flex-col gap-4">
            <h3 className="text-xs font-bold text-textt uppercase tracking-wider">Doctor&apos;s Clinical Notes & Suggestions</h3>
            {errorMsg && (
              <p className="text-xs font-bold text-rose-600 bg-rose-50 border border-rose-100 p-2.5 rounded-xl">{errorMsg}</p>
            )}
            <textarea
              rows={4}
              placeholder="Enter your observations, clinical diagnosis, or treatment recommendations here..."
              value={doctorNotes}
              onChange={(e) => setDoctorNotes(e.target.value)}
              className="w-full border border-bgelem/60 rounded-xl px-4 py-3 text-xs text-texts focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all font-semibold leading-relaxed"
            ></textarea>

            {/* Assessment Input & Checks */}
            <div className="flex flex-col gap-4 border-t border-bgelem/40 pt-4">
              <div className="flex flex-col gap-2">
                <label className="text-xs font-bold text-texts">Final Clinical Assessment</label>
                <select
                  value={doctorAssessment}
                  onChange={(e) => setDoctorAssessment(e.target.value)}
                  className="w-full border border-bgelem/60 rounded-xl px-4 py-2.5 text-xs text-texts focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all font-semibold"
                >
                  <option value="Normal">Normal</option>
                  <option value="Borderline">Borderline</option>
                  <option value="Cardiomegaly">Cardiomegaly</option>
                  <option value="Attention Required">Attention Required</option>
                </select>
              </div>

              <div className="flex flex-wrap items-center gap-6 mt-1">
                <label className="flex items-center gap-2 text-xs font-bold text-texts cursor-pointer">
                  <input
                    type="checkbox"
                    checked={aiAccuracyConfirmed}
                    onChange={(e) => setAiAccuracyConfirmed(e.target.checked)}
                    className="rounded border-bgelem text-primary focus:ring-primary h-4 w-4 cursor-pointer"
                  />
                  Confirm AI Accuracy
                </label>

                <label className="flex items-center gap-2 text-xs font-bold text-texts cursor-pointer">
                  <input
                    type="checkbox"
                    checked={ecgRequired}
                    onChange={(e) => setEcgRequired(e.target.checked)}
                    className="rounded border-bgelem text-primary focus:ring-primary h-4 w-4 cursor-pointer"
                  />
                  ECG Exam Required
                </label>
              </div>
            </div>
          </div>

          {/* Action buttons columns */}
          <div className="flex flex-col gap-3">
            <button
              onClick={handleSubmitVerification}
              disabled={submitting}
              className="w-full bg-primary hover:bg-primary/95 text-white font-bold rounded-xl py-3.5 text-xs transition-all flex items-center justify-center gap-2 cursor-pointer shadow-md shadow-primary/10 disabled:opacity-50"
            >
              <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              {submitting ? "Submitting..." : "Verify & Send Report to Patient"}
            </button>
          </div>
        </div>

        {/* Right Column (Patient profile and AI insights) */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          {/* Patient Profile Box */}
          <div className="bg-fbc border border-bgelem/30 rounded-2xl p-6 shadow-sm flex flex-col gap-4">
            <h3 className="text-[18px] font-bold text-texts tracking-tight">Patient Profile</h3>
            <div className="flex items-center gap-4 border-b border-bgelem pb-4">
              <div className="w-12 h-12 rounded-full bg-[#EAF2FC] text-primary font-bold text-sm flex items-center justify-center shrink-0">
                {patient.patientName.slice(0, 2).toUpperCase()}
              </div>
              <div>
                <h4 className="text-[16px] font-bold text-texts">{patient.patientName}</h4>
                <p className="text-[16px] text-textt font-semibold mt-0.5">Patient</p>
              </div>
            </div>
            <div className="flex justify-between items-center text-[16px]">
              <span className="font-regular text-textt">Blood Type</span>
              <span className="font-bold text-texts">{patient.bloodType}</span>
            </div>
            <div className="flex justify-between items-center text-[16px]">
              <span className="font-regular text-textt">Allergies</span>
              <span className="font-bold text-texts">{patient.allergies}</span>
            </div>
          </div>

          {/* AI Diagnostic Results Box */}
          <div className="bg-[#DEE8FF] border border-primary/10 rounded-2xl p-6 shadow-sm flex flex-col gap-5 ">
            <h3 className="text-[14px] text-[#434654] uppercase tracking-widest">AI Diagnostic Results</h3>

            {/* Split cards */}
            {(() => {
              const ctrVal = parseFloat(patient.ctrRatio);
              const isCtrHigh = !isNaN(ctrVal) && ctrVal > 0.50;
              const isCardiomegaly = patient.aiPrediction.toLowerCase().includes("cardiomegaly");
              return (
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-fbc border border-primary/5 rounded-r-xl p-4 flex flex-col border-l-4 border-l-primary">
                    <span className="text-[10px] font-semibold text-textt">CTR Ratio</span>
                    <span className="text-xl font-extrabold text-texts mt-1.5">{patient.ctrRatio}</span>
                    <span className={`text-[9px] font-bold mt-1 uppercase ${isCtrHigh ? 'text-rose-600' : 'text-emerald-600'}`}>
                      {isCtrHigh ? 'High' : 'Normal'}
                    </span>
                  </div>
                  <div className="bg-fbc border border-primary/5 rounded-r-xl p-4 flex flex-col border-l-4 border-l-primary">
                    <span className="text-[10px] font-semibold text-textt">Heart Size</span>
                    <span className="text-xl font-extrabold text-texts mt-1.5">{patient.heartSize}</span>
                    <span className={`text-[9px] font-bold mt-1 ${isCardiomegaly ? 'text-rose-600' : 'text-[#10B981]'}`}>
                      {isCardiomegaly ? 'Enlarged' : 'No enlargement'}
                    </span>
                  </div>
                </div>
              );
            })()}

            {/* AI Insight Box */}
            <div className="bg-white border border-primary/5 rounded-2xl p-5 h-[190px] w-full max-w-[366px] shadow-sm flex flex-col justify-start shrink-0">
              <div className="flex flex-col gap-2.5 h-full overflow-y-auto">
                <span className="text-[11px] font-bold text-texts uppercase tracking-wider flex items-center gap-1.5 shrink-0">
                  <svg className="w-4 h-4 text-texts" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                  </svg>
                  AI Insight
                </span>
                <p className="text-[10px] text-texts font-semibold leading-relaxed">
                  {patient.aiInsight}
                </p>
              </div>
            </div>
          </div>

          {/* Patient Notes / Symptoms Box */}
          <div className="bg-fbfc border border-bgelem/30 rounded-2xl p-6 shadow-sm flex flex-col gap-3">
            <h3 className="text-[18px] font-semibold text-texts tracking-tight">Patient Notes</h3>
            <p className="text-[16px] text-textt  italic leading-relaxed bg-bgelem/40 p-5 border border-bgelem/30 rounded-xl">
              &quot;{patient.symptoms}&quot;
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function DetailAnalysis() {
  return (
    <Suspense fallback={
      <div className="w-full h-96 flex items-center justify-center bg-fbc rounded-2xl border border-bgelem/40">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
          <p className="text-xs font-bold text-textt">Loading analysis details...</p>
        </div>
      </div>
    }>
      <DetailAnalysisContent />
    </Suspense>
  );
}
